FROM node:argon
ARG UID

RUN mkdir /home/supjirallo
RUN npm install -g mocha

RUN useradd -u $UID -m docker && echo "docker:docker" | chpasswd

COPY . /home/supjirallo

WORKDIR /home/supjirallo

CMD sleep 10s; mocha --recursive -w tests; 

